Ww3 spec
NOAA-EMC/WW3-tools pull request #24
Opened 2022-12-09 01:15 UTC by aliabdolali

# Pull Request Summary
add three matlab functions:

write_directional_spectra_ascii.m
write_directional_spectra_nc.m 
convert_time.m 

## Description
write_directional_spectra_ascii.m to write directional spectral density file in WW3 format (ascii)
write_directional_spectra_nc.m to write directional spectral density file in WW3 format (netcdf)
convert_time.m to read time from netcdf and convert to matlab time (read reference date and unit from time variable and adjust)

Provide a detailed description of what this PR does.
new feature, to provide an option for the users to generate boundary conditions for WW3 model.

Please also include the following information: 
_enhancement_, _new feature_

### Commit Message
add functions to write directional spectral density files in WW3 format (ascii and nc)

### Check list  

- [x] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing

* How were these changes tested?
These funtions have been tested for Boes cases and wave vegetation cases in WW3.

2022-12-20 23:27 UTC, MatthewMasarik-NOAA commented on tools/convert_time.m
> +% This program cobverts the time variable in the netcdf file relative to  %
converts

2022-12-20 23:27 UTC, MatthewMasarik-NOAA commented on tools/convert_time.m
> +% unit origin (unit attrivute)to matlab time                              %
attribute

2022-12-20 23:35 UTC, MatthewMasarik-NOAA requested changes
First commit for 3 matlab `tools/` scripts, developer has tested.  Code review requests correction of two typos, otherwise passes.

2022-12-21 13:13 UTC, MatthewMasarik-NOAA commented
@aliabdolali please edit typos then I will merge this PR.

2022-12-21 14:05 UTC, aliabdolali commented
> @aliabdolali please edit typos then I will merge this PR.

Done!!!!

2022-12-21 14:06 UTC, MatthewMasarik-NOAA approved these changes
Thank you @aliabdolali for contributing these utility scripts for the community to use.

2022-12-21 14:08 UTC, merged