Altimeter
NOAA-EMC/WW3-tools pull request #36
Opened 2023-09-18 17:03 UTC by Ghazal-Mohammadpour

# Pull Request Summary
Create satellite information by time and optionally with time averaging.

## Description

This pull request represents the initial phase towards achieving our overarching goal. The primary objective is to process previously downloaded satellite data organized by latitude/longitude buckets and create files containing satellite data grouped by specified time intervals (e.g., day, month, year). 

Please also include the following information: 

- Extension:
In addition to creating single files per time period, this routine will be enhanced to support the creation of time-averaged values of the data at specified time intervals (e.g., every X seconds).

- Purpose:
This pull request addresses the need to efficiently organize and process satellite data, making it more accessible and useful for subsequent analysis. It aims to improve data management and provide the foundation for future data processing tasks.

- Bug Fix or Feature Addition:
This pull request does not fix a specific bug but rather adds a new feature to the project. It introduces a script that streamlines the organization of satellite data into manageable chunks of time, enhancing data accessibility and usability for scientific analysis.

- Suggestions for Reviewer:

1. Reviewers are encouraged to assess the code for efficiency and accuracy in handling the specified inputs and producing the expected outputs.

2. Verify that the script correctly handles different time bounds (e.g., day, month, year) and optional quality control features.

3. Ensure that the documentation is clear and comprehensive, providing sufficient guidance on using the script and its inputs.

### Issue(s) addressed

### Commit Message
```
feat: Introduce script for satellite data organization and NetCDF file creation

This commit adds a new script to process previously downloaded satellite data from AODN, organizing it by specified time intervals (e.g., day, month, year), and creating NetCDF files with observation time, location, significant wave height (HS), wind speed, and optional satellite ID and quality control information.

- Script handles input directory location, satellite selection, and time bounds.
- Future extension to support time-averaged data creation.

See detailed PR description for more information.
```

### Check list  

- [ ] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing

These new features tested with test runs using several satellite data.

2023-09-18 17:08 UTC, JessicaMeixner-NOAA commented
@Ghazal-Mohammadpour  thank you so much for creating this PR!   It looks like you unintentionally added a second under the pycache folder.  Can you remove that if it was unintentional?

2023-09-18 17:10 UTC, Ghazal-Mohammadpour commented
Hi Jessica,

I will remove it. Thanks for letting me know.

Regards,
Ghazal

On Mon, Sep 18, 2023 at 10:08 AM Jessica Meixner ***@***.***>
wrote:

> @Ghazal-Mohammadpour <https://github.com/Ghazal-Mohammadpour> thank you
> so much for creating this PR! It looks like you unintentionally added a
> second under the pycache folder. Can you remove that if it was
> unintentional?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/WW3-tools/pull/36#issuecomment-1724018847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5W2POF5P3IFTT6NLZ4UUI3X3B5ZBANCNFSM6AAAAAA45A7I7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-27 21:05 UTC, JessicaMeixner-NOAA reviewed
Thanks @Ghazal-Mohammadpour for this work! I've made a few comments and will need some additional explanation before I can test and finish the review.  Looking forward to having this new capability!

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +    sdname = 'JASON2'
It would be good to have this as an input just like the "time-averaging" option is.

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +    sname = 'JASON-2'
This could be determined based on the sdname input so you don't have to input both of these options via a table of sorts.

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +    start_date = datetime.datetime(2012, 1, 1, 0, 0, 0)
Can this be added to the inputs?

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +    parser.add_argument('-i', '--input', help="Path to input file")
Can you tell me a little more about what input file this is specifically? For example is it the directory where the satellite input files are?

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +            output_file = f"{sdname}_time_averaged_data.nc"
It might be helpful to have the date range in the file names along with the satelite name and if it's time-averaged, what is the averaging time.

2023-09-27 21:05 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter_switch.py
> +#USAGE:
Can this usage statement be updated a bit so I know how to test this?   At this time, I don't have quite enough information to test at this moment. 

Also, ideally we'll have an option to turn on/off the time-avaeraging and there's no need to have both this and the other file without the option.

2023-10-06 14:11 UTC, JessicaMeixner-NOAA requested changes
A few small comments, also waiting on updates based on offline communication.

2023-10-06 14:11 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter.py
> +#The provided Python script (SatGlobal_Altimeter_new.py) is designed to process satellite data based on the input parameters you provide.
```suggestion
#The provided Python script (SatGlobal_Altimeter.py) is designed to process satellite data based on the input parameters you provide.
```

2023-10-06 14:11 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter.py
> +    parser.add_argument('--sdname', required=True, help='Satellite directory name')
Can we simplify to only have one of these? Either sname or sdname and then have a list that tells you what the other is based on the first list? 

Should a list of valid or potential values be listed as options here or in the comments at the beginning of the code?

2023-10-06 14:11 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter.py
> +    parser.add_argument('-i', '--input', required=True, help='Input directory path')
Can you explain here or somewhere a little more about what the input directory is supposed to be?   For example and input directory of downloaded sat files ?

2023-10-12 12:36 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter.py
> +#-i or --input: This required argument expects users to provide the path to an input directory. It is likely the directory where satellite data files are located.
@GhazalMohammadpour-NOAA  Your comment here says that the input directory is "likely" the directory where the satelite files are located.  Would this program work if the input directory was not the directory where the satellite files are located?

2023-10-12 12:37 UTC, JessicaMeixner-NOAA commented on ww3tools/SatGlobal_Altimeter.py
> +#-i or --input: This required argument expects users to provide the path to an input directory. It is likely the directory where satellite data files are located.
I recommend removing the word "likely" and simply just saying it is the directory where the satellite files are located.

2023-10-13 14:33 UTC, JessicaMeixner-NOAA commented
@Ghazal-Mohammadpour I tested your code this morning however I ran into an issue where most files did not exist: 
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-360E-DM00.nc does not exist

I believe this is because sname had a space at the end of it.  I'm testing a minor update which you can find here: https://github.com/JessicaMeixner-NOAA/WW3-tools/tree/update2altimeter  this is now running.   I'll be running a few more tests throughout the day, but I was curious if you had run into this issue or not.

2023-10-13 15:36 UTC, GhazalMohammadpour-NOAA commented
It reads all the longitudes and latitudes. And it will skip the ones that
it does not have for the track of measurement. So if there is a track with
that specific lon/lat it will read, but if it does not, it will skip.

On Fri, Oct 13, 2023 at 10:33 AM Jessica Meixner ***@***.***>
wrote:

> @Ghazal-Mohammadpour <https://github.com/Ghazal-Mohammadpour> I tested
> your code this morning however I ran into an issue where most files did not
> exist:
> File
> /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-360E-DM00.nc
> does not exist
>
> I believe this is because sname had a space at the end of it. I'm testing
> a minor update which you can find here:
> https://github.com/JessicaMeixner-NOAA/WW3-tools/tree/update2altimeter
> this is now running. I'll be running a few more tests throughout the day,
> but I was curious if you had run into this issue or not.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/WW3-tools/pull/36#issuecomment-1761624381>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BA6FDZMTJAZSGHEJ5Q6VYSDX7FGMNANCNFSM6AAAAAA45A7I7A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-13 15:40 UTC, JessicaMeixner-NOAA commented
@GhazalMohammadpour-NOAA The issue was that it found no valid data at all, even though there should have been, see for example the output last several lines: 

```
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-354E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-355E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-356E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-357E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-358E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-359E-DM00.nc does not exist
File /scratch2/NCEPDEV/marine/Matthew.Masarik/dat/sat/AODN/altimeter/JASON2/IMOS_SRS-Surface-Waves_MW_JASON-2 _FV02_090N-360E-DM00.nc does not exist
Done reading and allocating satellite data for JASON-2 
No valid data found for JASON-2 
Job completed.
```

My concern is the space between JASON-2 and _FV02_090N.   However, when I updated the file to only have an input for sdname there was valid data even though I did not change the time period.

2023-10-13 20:14 UTC, JessicaMeixner-NOAA commented
@Ghazal-Mohammadpour  I was able to run with my minor updates to your code a few scenarios with different averaging time.  I still need to test a different satellite and make some plots to confirm everything is doing what is expected.  I'd be interested to see your output for running this file without the modifications to see if I'm doing something wrong on my end while testing, although I did follow your instructions.

2023-10-13 20:18 UTC, Ghazal-Mohammadpour commented
I can send you the path to the results if you need to double check.

On Fri, Oct 13, 2023 at 1:15 PM Jessica Meixner ***@***.***>
wrote:

> @Ghazal-Mohammadpour <https://github.com/Ghazal-Mohammadpour> I was able
> to run with my minor updates to your code a few scenarios with different
> averaging time. I still need to test a different satellite and make some
> plots to confirm everything is doing what is expected. I'd be interested to
> see your output for running this file without the modifications to see if
> I'm doing something wrong on my end while testing, although I did follow
> your instructions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/WW3-tools/pull/36#issuecomment-1762146388>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5W2POBSLPAM5BPPOAMI6KLX7GOMXAVCNFSM6AAAAAA45A7I7CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRSGE2DMMZYHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-13 20:19 UTC, JessicaMeixner-NOAA commented
> I can send you the path to the results if you need to double check.

That would be great, thanks!

2023-10-13 20:21 UTC, Ghazal-Mohammadpour commented
Sure thing. Thank you for your time.

On Fri, Oct 13, 2023 at 1:19 PM Jessica Meixner ***@***.***>
wrote:

> I can send you the path to the results if you need to double check.
>
> That would be great, thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/WW3-tools/pull/36#issuecomment-1762150691>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5W2POEX2JK6RDNFHAC2KKTX7GO6JAVCNFSM6AAAAAA45A7I7CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRSGE2TANRZGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-13 20:33 UTC, JessicaMeixner-NOAA commented
@GhazalMohammadpour-NOAA Thanks for sending the paths -  I did a quick diff and I see we have some description differences which look like were added just to github but also some code diffs: 

```
< 
119c95
<                     hsk = fu.variables['SWH_KU'][:]
---
>                     hsk = fu.variables['SWH_C'][:]
127c103
<                     hsk = fu.variables['SWH_KA'][:]
---
>                     hsk = fu.variables['SWH_C'][:]
296d271
< 
```

Is the code in GitHub the correct one?

2023-10-13 20:36 UTC, Ghazal-Mohammadpour commented
Yes, that's it!

On Fri, Oct 13, 2023 at 1:33 PM Jessica Meixner ***@***.***>
wrote:

> @GhazalMohammadpour-NOAA <https://github.com/GhazalMohammadpour-NOAA>
> Thanks for sending the paths - I did a quick diff and I see we have some
> description differences which look like were added just to github but also
> some code diffs:
>
> <
> 119c95
> <                     hsk = fu.variables['SWH_KU'][:]
> ---
> >                     hsk = fu.variables['SWH_C'][:]
> 127c103
> <                     hsk = fu.variables['SWH_KA'][:]
> ---
> >                     hsk = fu.variables['SWH_C'][:]
> 296d271
> <
>
> Is the code in GitHub the correct one?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/WW3-tools/pull/36#issuecomment-1762163879>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5W2POFJFZDBTEGF57WEGWLX7GQQ5AVCNFSM6AAAAAA45A7I7CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRSGE3DGOBXHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-14 01:51 UTC, JessicaMeixner-NOAA commented
Okay I ran the other script from your directory and got an output file, so I'm not sure what exactly was wrong when I first ran things.  Either way, more info to come on Monday.

2023-10-16 15:22 UTC, JessicaMeixner-NOAA commented
It's my understanding that work in this PR is included in PR #37 and this PR can be closed. I will stop reviewing this PR unless I hear differently.

2023-10-26 13:21 UTC, JessicaMeixner-NOAA commented
@GhazalMohammadpour-NOAA was this going to be closed?

2023-10-30 15:36 UTC, closed without merging