Adding window_mask.py for variable unstructured mesh, and revising th…
NOAA-EMC/WW3-tools pull request #56
Opened 2024-04-15 17:32 UTC by AliS-Noaa

…e spacing.py and ocn_ww3.py to read the mask file, addressing issue #55

# Pull Request Summary
 
Adding variable mesh spacing capability for unstructured mesh generation. 

## Description

1.  Adds a window_mask.py to generate variable mesh spacing for unstructured mesh.
2. Revises the spacing.py and ocn_ww3.py to read the mesh spacing netcdf file.
3. Revised the READM.md to give instruction how to use the new scripts.

### Issue(s) addressed

Addresses issue #55 
### Commit Message

### Check list  

- [] Branch is up to date with the authoritative repository (NOAA-EMC) develop branch. 
 
### Testing

* How were these changes tested?

2024-04-16 15:01 UTC, JessicaMeixner-NOAA commented
@AliS-Noaa please add a commit message in the PR template

2024-04-16 15:15 UTC, JessicaMeixner-NOAA commented
@sbanihash Have you run the variable resolution unstructured mesh scripts in this PR yet using the README?

2024-04-16 15:24 UTC, sbanihash commented
@JessicaMeixner-NOAA Not yet.

2024-04-16 15:28 UTC, JessicaMeixner-NOAA commented
Okay - can you let me know if/when you do.  I'm having some issues and curious if it's just a me problem. 

In the meantime, @AliS-Noaa can you share where you have rocky-8 modules on hera for the python env?

2024-04-16 15:36 UTC, AliS-Noaa commented
@JessicaMeixner-NOAA @sbanihash looks like my modules have some issue with the Rocy8. I can not load them, but you should be able to run them on orion. In meantime, I will take care of the HERA modules.

2024-04-16 16:45 UTC, JessicaMeixner-NOAA commented
@AliS-Noaa thank you for addressing the hera issues.  I will use orion in the meantime.  Can you provide additional information about how to define multiple windows?  Perhaps you can share the example of how you created the grid combining multi-1 and gfsv16 resolutions as a sample case for us to try to recreate?

2024-04-16 16:52 UTC, AliS-Noaa commented
@JessicaMeixner-NOAA this is how you can create the GFSv16 like mesh: 
python3 window_mask.py --windows '[{"min_lon": -98, "max_lon": -64, "min_lat": 24, "max_lat": 44.5, "hshr": 5}, {"min_lon": -158, "max_lon": -155, "min_lat": 19, "max_lat": 22, "hshr": 5}, {"min_lon": -128, "max_lon": -64, "min_lat": 34.5, "max_lat": 48.5, "hshr": 5}, {"min_lon": -67.4, "max_lon": -64.1, "min_lat": 17.2, "max_lat": 18.3, "hshr": 5}]'

2024-04-16 17:55 UTC, JessicaMeixner-NOAA commented
Thanks for providing an example.  Would you mind adding this to the readme or a usage/help statement in the code?

2024-04-19 21:00 UTC, JessicaMeixner-NOAA requested changes

2024-04-19 21:00 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/window_mask.py
> +    # Define the boundaries and scaling values
Please provide additional information of the following variables.

2024-04-19 21:00 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/ocn_ww3.py
> +    opts.hfun_hmax = 100.           # uniform at 30.km
Please provide a note here about how this variable should be defined and what it means.  Additional descriptions of the other opts. variables would also be appreciated.

2024-04-19 21:00 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/ocn_ww3.py
> +    dhdx = 0.05  # allowable spacing gradient
Additional information about how this variable relates to mesh quality would be very helpful to users.  

A note if/how these variables are used if you have an input from a mask file would be appreciated.

2024-04-19 21:00 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/README.md
> +6- Using variable mode:
Please note that the markdown formatting is not quite as expected when you look at this document in github.  An update in formatting would improve readability in github.

2024-04-19 21:00 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/README.md
> +
Please add an example here or somewhere else in the code about how to define multiple windows.

2024-04-22 17:35 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/window_mask.py
> +    upper_bound = 50       # for lat > 50N
@AliS-Noaa what about some details such as: 

```
    upper_bound = 50       # Lattitude that starts the upper section (ie lat > upper_bound) 
    middle_bound = -20     # Determines the boundary between the upper  and middle sections.  The middle section is for upper_bound > lat > middle_bound 
    lower_bound = -90      # Boundary of lowest section, likely -90,   Lower section is:   middle_bound > lat > lower_bound
    scale_north = 9        # mesh resolution  in km for upper section ( lat > upper_bound )
    scale_middle = 20      # mesh resolution in km for  middle section for middle_bound < lat < upper_bound
# Mesh resolution of the lower section is linear from scale_south_upper to scale_south_upper
    scale_south_upper = 30 # km resolution for upper south/lower section 
    scale_south_lower = 9  # km mesh resolution at lower south/lower section 
```

2024-04-22 18:29 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/README.md
> +- upper_bound = 50          # for lat > 50N
@AliS-Noaa this would benefit from the updates you made in the other routine to add them here too.

2024-04-23 13:09 UTC, JessicaMeixner-NOAA commented on unst_msh_gen/README.md
> +## 2- you need following packages:
@AliS-Noaa this is different from the list you gave me: 

$ python3 -m pip install scipy
$ python3 -m pip install imageio
$ python3 -m pip install scikit-image
$ python3 -m pip install tifffile
$ python3 -m pip install certifi
$ python3 -m pip install cftime
$ python3 -m pip install netCDF4
$ python3 -m pip install network
$ python3 -m pip install packaging
$ python3 -m pip install pillow
$ python3 -m pip install setuptools

I know some of these are installed already when you install other modules, but wanted to check to see if this list should be updated?

2024-04-23 18:13 UTC, JessicaMeixner-NOAA approved these changes

2024-04-23 18:14 UTC, merged